[project]
name = "index"
version = "0.1.0"
description = "Add a short description here"
authors = ["Peter Van Sandt <peter.vansandt@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64", "linux-64"]

[tasks]
pwd = "pwd"
configure = "cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -S. -B.build"
build = "cmake --build .build"
test = { cmd = "pixi run ninja test -C.build", depends-on = ["build"] }
run = { cmd = ".build/index", depends-on = ["build"] }
release = "cmake -DCMAKE_BUILD_TYPE=Release -GNinja -S. -B.build-rel ; cmake --build .build-rel ; .build-rel/index"

[dependencies]
cxx-compiler = ">=1.7.0,<1.8"
benchmark = ">=1.8.4,<1.9"
cmake = ">=3.29.6,<3.30"
ninja = ">=1.12.1,<1.13"
